DeckDictSpirit  =  { "flooded_strand" :2, 
                     "forest" :1,
                     "hallowed_fountain" : 1,
                     "horizon_canopy" :3 ,
                     "island" :1,
                     "misty_rainforest" :3,
                     "moorland_haunt" :1,
                     "plains" :1,
                     "seachrome_coast" :1,
                     "temple_garden" :1 ,
                     "windswept_heath" :2,
                     "drogskol_captain" :4,
                     "geist_of_saint_traft" :2,
                     "mausoleum_wanderer" :4,
                     "noble_hierarch" :4,
                     "phantasmal_image" :3,
                     "rattlechains" :1,
                     "selfless_spirit" :2,
                     "spell_queller" :4,
                     "supreme_phantom" :4,
                     "collected_company" :4,
                     "path_to_exile" :4,
                     "aether_vial" :3,
                     "botanical_sanctum" :2,
                     "breeding_pool" :1,
                     "cavern_of_souls" :1}