DeckDictBurn =    {"wooded_foothills" :4,
                "stomping_ground"  :1,
                "sacred_foundry"  :2,
                "mountain" :3,
                "inspiring_vantage" :4,
                "bloodstained_mire" :4,
                "arid_mesa" :2,
                "skullcrack" :4,
                "searing_blaze" :4,
                "lightning_helix" :4,
                "lightning_bolt" : 4,
                "boros_charm" :4,
                "rift_bolt" :4,
                "lava_spike" :4,
                "monastery_swiftspear" :4,
                "goblin_guide" :4,
                "eidolon_of_the_great_revel" :4}