DeckDictHumans  =  {"island":1,
                    "plains":1,
                    "seachrome_coast":1,
                    "unclaimed_territory":4,
                    "ancient_ziggurat":4,
                    "cavern_of_souls":4,
                    "horizon_canopy":4,
                    "aether_vial":4,
                    "noble_hierarch":4,
                    "champion_of_the_parish":4,
                    "kitesail_freebooter":4,
                    "meddling_mage":4,
                    "phantasmal_image":4,
                    "thalia_guardian_of_thraben":3,
                    "thalia_lieutenant":4,
                    "mantis_rider":4,
                    "militia_bugler":3,
                    "reflector_mage":3}